name: Build Kernel Module

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Install aarch64 cross compiler
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu make flex bison libssl-dev

      - name: Download kernel source 5.10.252
        run: |
          # 1. 下载内核源码（使用官方全球边缘加速镜像，速度极快）
          wget -q --timeout=60 --tries=5 https://mirrors.edge.kernel.org/pub/linux/kernel/v5.x/linux-5.10.252.tar.xz
          
          # 2. 解压并进入目录
          tar -xf linux-5.10.252.tar.xz
          cd linux-5.10.252
          
          # 3. 核心修复：配置和准备内核时，必须加上 CROSS_COMPILE 参数指定 aarch64 编译器
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules_prepare

      - name: Compile LKM .ko module
        run: |
          # 编译你自己的驱动模块
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KERNELDIR=$PWD/linux-5.10.252 M=$PWD modules

      - name: Upload compiled ko artifact
        uses: actions/upload-artifact@v5
        with:
          name: cpu_spoof_ko
          path: ./*.ko        with:
          name: cpu_spoof_ko
          path: ./*.ko
